##################################################################################################

# Main  service receiving response from ingress

##################################################################################################

apiVersion: v1

kind: Service

metadata:

  name: customers-service

  labels:

    app: customers-service

spec:

  ports:

  - port: 8080

    name: http

  selector:

    app: customers-service

---

apiVersion: extensions/v1beta1

kind: Deployment

metadata:

  name: customers-service-deployment-v1

spec:

  replicas: 1

  template: # template for the pods

    metadata:

      labels:

        app: customers-service

        version: v1

    spec:

      containers:

      - name: customers-service

        image: saurabh2204/spring-petclinic-customers-service-istio:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 8080

---

##################################################################################################

# Hello message services being called by main service

##################################################################################################

apiVersion: v1

kind: Service

metadata:

  name: vets-service

  labels:

    app: vets-service

spec:

  ports:

  - port: 8888

    name: http

  selector:

    app: vets-service

  type: ClusterIP

---

apiVersion: extensions/v1beta1

kind: Deployment

metadata:

  name: vets-service-deployment-v1

spec:

  replicas: 1

  template: # template for the pods

    metadata:

      labels:

        app: vets-service

        version: v1

    spec:

      containers:

      - name: vets-service

        image: saurabh2204/spring-petclinic-vets-service-istio:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 8888

---
